services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.development
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./frontend/:/src

  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.sidekiq.development
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

volumes:
  postgres:
