FROM ruby:3.2.2

RUN apt update && apt install -y nodejs postgresql-client
RUN mkdir /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler

COPY . .
RUN bundle install

CMD ["bundle", "exec", "sidekiq"]
